Repository Media-XI/artscope-backend, pull requests merged in 2024-04, with the labels that each got.

#155 feat : 팀, 팀유저 관련 기능 추가
  src/main/java/com/example/codebase/controller/TeamController.java
  src/main/java/com/example/codebase/controller/TeamUserController.java
  src/main/java/com/example/codebase/domain/member/entity/Member.java
  src/main/java/com/example/codebase/domain/team/dto/TeamRequest.java
  src/main/java/com/example/codebase/domain/team/dto/TeamResponse.java
  src/main/java/com/example/codebase/domain/team/dto/TeamUserRequest.java
  src/main/java/com/example/codebase/domain/team/dto/TeamUserResponse.java
  src/main/java/com/example/codebase/domain/team/entity/Team.java
  src/main/java/com/example/codebase/domain/team/entity/TeamUser.java
  src/main/java/com/example/codebase/domain/team/entity/TeamUserRole.java
  src/main/java/com/example/codebase/domain/team/repository/TeamRepository.java
  src/main/java/com/example/codebase/domain/team/repository/TeamUserRepository.java
  src/main/java/com/example/codebase/domain/team/service/TeamService.java
  src/main/java/com/example/codebase/domain/team/service/TeamUserService.java
  src/main/resources/db/migration/V202403051155__application.sql
  src/main/resources/db/migration/V202403051156__application.sql
  src/test/java/com/example/codebase/controller/TeamControllerTest.java
  src/test/java/com/example/codebase/controller/TeamUserControllerTest.java
  src/test/java/com/example/codebase/domain/team/repository/TeamRepositoryTest.java
  src/test/java/com/example/codebase/domain/team/service/TeamUserServiceTest.java
Labels: D-3

#156 [PR] 팀 팔로잉 기능
  src/main/java/com/example/codebase/controller/FollowController.java
  src/main/java/com/example/codebase/domain/follow/dto/FollowDetailResponseDTO.java
  src/main/java/com/example/codebase/domain/follow/dto/FollowMemberDetailResponseDTO.java
  src/main/java/com/example/codebase/domain/follow/dto/FollowMembersResponseDTO.java
  src/main/java/com/example/codebase/domain/follow/dto/FollowRequest.java
  src/main/java/com/example/codebase/domain/follow/dto/FollowResponseDTO.java
  src/main/java/com/example/codebase/domain/follow/entity/Follow.java
  src/main/java/com/example/codebase/domain/follow/entity/FollowIds.java
  src/main/java/com/example/codebase/domain/follow/repository/FollowRepository.java
  src/main/java/com/example/codebase/domain/follow/service/FollowService.java
  src/main/java/com/example/codebase/domain/magazine/repository/MagazineRepository.java
  src/main/java/com/example/codebase/domain/member/entity/Member.java
  src/main/java/com/example/codebase/domain/team/repository/TeamRepository.java
  src/main/java/com/example/codebase/exception/DuplicatedRequestException.java
  src/main/resources/db/migration/V202403051157__application.sql
  src/test/java/com/example/codebase/controller/CurationControllerTest.java
  src/test/java/com/example/codebase/controller/FollowControllerTest.java
Labels: D-2

#158 [PR] 좋아요한 매거진 표시 기능
  src/main/java/com/example/codebase/domain/magazine/dto/MagazineResponse.java
  src/main/java/com/example/codebase/domain/magazine/entity/MagazineWithIsLiked.java
  src/main/java/com/example/codebase/domain/magazine/repository/MagazineRepository.java
  src/main/java/com/example/codebase/domain/magazine/service/MagazineService.java
  src/main/java/com/example/codebase/util/SecurityUtil.java
  src/test/java/com/example/codebase/controller/MagazineLikeControllerTest.java
Labels: D-1

#157 feat 메거진 팀 글쓰기 기능
  src/main/java/com/example/codebase/annotation/CheckDuplicatedRequest.java
  src/main/java/com/example/codebase/aop/CheckDuplicatedRequestAspect.java
  src/main/java/com/example/codebase/controller/MagazineController.java
  src/main/java/com/example/codebase/domain/magazine/dto/MagazineRequest.java
  src/main/java/com/example/codebase/domain/magazine/dto/MagazineResponse.java
  src/main/java/com/example/codebase/domain/magazine/entity/Magazine.java
  src/main/java/com/example/codebase/domain/magazine/repository/MagazineRepository.java
  src/main/java/com/example/codebase/domain/magazine/service/MagazineService.java
  src/main/java/com/example/codebase/domain/team/entity/Team.java
  src/main/java/com/example/codebase/domain/team/service/TeamService.java
  src/main/resources/db/migration/V202403051158__application.sql
  src/test/java/com/example/codebase/aop/CheckDuplicatedRequestAspectMock.java
  src/test/java/com/example/codebase/controller/CurationControllerTest.java
  src/test/java/com/example/codebase/controller/MagazineCategoryControllerTest.java
  src/test/java/com/example/codebase/controller/MagazineControllerTest.java
Labels: D-3

#160 [PR] 팀 정보 반환 기능 추가
  src/main/java/com/example/codebase/domain/member/dto/MemberResponseDTO.java
  src/main/java/com/example/codebase/domain/member/entity/Member.java
  src/main/java/com/example/codebase/domain/member/service/MemberService.java
  src/main/java/com/example/codebase/domain/team/dto/TeamResponse.java
  src/main/java/com/example/codebase/domain/team/dto/TeamUserResponse.java
  src/main/java/com/example/codebase/domain/team/entity/TeamUser.java
  src/test/java/com/example/codebase/controller/MemberControllerTest.java
  src/test/java/com/example/codebase/controller/TeamControllerTest.java
Labels: D-1

#162 내 정보 조회 API 이관 및 사용자 정보 조회 관련 작업
  .github/workflows/test.yaml
  src/main/java/com/example/codebase/controller/AuthController.java
  src/main/java/com/example/codebase/controller/MemberController.java
  src/main/java/com/example/codebase/domain/member/dto/MemberResponseDTO.java
  src/test/java/com/example/codebase/controller/AuthControllerTest.java
  src/test/java/com/example/codebase/controller/MemberControllerTest.java
Labels: D-3

#163 Art 184 be 내가 속한 팀 정보 api 응답 데이터 수정
  src/main/java/com/example/codebase/controller/MemberController.java
  src/main/java/com/example/codebase/controller/TeamController.java
  src/main/java/com/example/codebase/controller/TeamUserController.java
  src/main/java/com/example/codebase/domain/member/dto/MemberResponseDTO.java
  src/main/java/com/example/codebase/domain/member/service/MemberService.java
  src/main/java/com/example/codebase/domain/team/dto/TeamResponse.java
  src/main/java/com/example/codebase/domain/team/repository/TeamUserRepository.java
  src/main/java/com/example/codebase/domain/team/service/TeamUserService.java
  src/test/java/com/example/codebase/controller/MemberControllerTest.java
  src/test/java/com/example/codebase/controller/TeamControllerTest.java
Labels: D-2
