Repository Media-XI/artscope-backend, pull requests merged in 2024-03, with the labels that each got.

#128 매거진 댓글, 좋아요, 조회수 기능 구현
  src/main/java/com/example/codebase/controller/MagazineCategoryController.java
  src/main/java/com/example/codebase/controller/MagazineController.java
  src/main/java/com/example/codebase/controller/MagazineLikeController.java
  src/main/java/com/example/codebase/domain/magazine/dto/MagazineCommentRepsonse.java
  src/main/java/com/example/codebase/domain/magazine/dto/MagazineCommentRequest.java
  src/main/java/com/example/codebase/domain/magazine/dto/MagazineRequest.java
  src/main/java/com/example/codebase/domain/magazine/dto/MagazineResponse.java
  src/main/java/com/example/codebase/domain/magazine/entity/Magazine.java
  src/main/java/com/example/codebase/domain/magazine/entity/MagazineComment.java
  src/main/java/com/example/codebase/domain/magazine/entity/MagazineLike.java
  src/main/java/com/example/codebase/domain/magazine/repository/MagazineCommentRepository.java
  src/main/java/com/example/codebase/domain/magazine/repository/MagazineLikeRepository.java
  src/main/java/com/example/codebase/domain/magazine/repository/MagazineRepository.java
  src/main/java/com/example/codebase/domain/magazine/service/MagazineLikeService.java
  src/main/java/com/example/codebase/domain/magazine/service/MagazineService.java
  src/main/java/com/example/codebase/util/SecurityUtil.java
  src/main/resources/application-test.yml
  src/main/resources/db/migration/V202402151700__create_magazine_comment.sql
  src/main/resources/db/migration/V202402291700__create_magazine_like_table.sql
  src/test/java/com/example/codebase/controller/MagazineControllerTest.java
  src/test/java/com/example/codebase/controller/MagazineLikeControllerTest.java
Labels: D-2

#129 매거진 미디어 업로드 기능 구현
  src/main/java/com/example/codebase/controller/MagazineController.java
  src/main/java/com/example/codebase/domain/magazine/dto/MagazineRequest.java
  src/main/java/com/example/codebase/domain/magazine/dto/MagazineResponse.java
  src/main/java/com/example/codebase/domain/magazine/entity/Magazine.java
  src/main/java/com/example/codebase/domain/magazine/entity/MagazineMedia.java
  src/main/java/com/example/codebase/domain/magazine/repository/MagazineMediaRepository.java
  src/main/java/com/example/codebase/domain/magazine/service/MagazineService.java
  src/main/resources/db/migration/V202403011600__create_magazine_media_table.sql
  src/test/java/com/example/codebase/controller/MagazineControllerTest.java
Labels: D-1

#127 Artdev 135 be 알람 기능
  src/main/java/com/example/codebase/config/RedisConfig.java
  src/main/java/com/example/codebase/config/S3Config.java
  src/main/java/com/example/codebase/controller/FollowController.java
  src/main/java/com/example/codebase/controller/MemberController.java
  src/main/java/com/example/codebase/controller/NotificationController.java
  src/main/java/com/example/codebase/controller/NotificationSettingController.java
  src/main/java/com/example/codebase/domain/follow/entity/Follow.java
  src/main/java/com/example/codebase/domain/follow/service/FollowService.java
  src/main/java/com/example/codebase/domain/member/entity/Member.java
  src/main/java/com/example/codebase/domain/member/service/MemberService.java
  src/main/java/com/example/codebase/domain/notification/dto/NotificationMessageRequest.java
  src/main/java/com/example/codebase/domain/notification/dto/NotificationResponse.java
  src/main/java/com/example/codebase/domain/notification/dto/NotificationSettingResponse.java
  src/main/java/com/example/codebase/domain/notification/entity/Notification.java
  src/main/java/com/example/codebase/domain/notification/entity/NotificationMessageFormatter.java
  src/main/java/com/example/codebase/domain/notification/entity/NotificationReceivedStatus.java
  src/main/java/com/example/codebase/domain/notification/entity/NotificationReceivedStatusIds.java
  src/main/java/com/example/codebase/domain/notification/entity/NotificationSetting.java
  src/main/java/com/example/codebase/domain/notification/entity/NotificationType.java
  src/main/java/com/example/codebase/domain/notification/entity/NotificationWithIsRead.java
  src/main/java/com/example/codebase/domain/notification/repository/NotificationReceivedStatusRepository.java
  src/main/java/com/example/codebase/domain/notification/repository/NotificationRepository.java
  src/main/java/com/example/codebase/domain/notification/repository/NotificationSettingRepository.java
  src/main/java/com/example/codebase/domain/notification/service/NotificationEventService.java
  src/main/java/com/example/codebase/domain/notification/service/NotificationSendService.java
  src/main/java/com/example/codebase/domain/notification/service/NotificationSendServiceImpl.java
  src/main/java/com/example/codebase/domain/notification/service/NotificationService.java
  src/main/java/com/example/codebase/domain/notification/service/NotificationSettingService.java
  src/main/java/com/example/codebase/util/RedisUtil.java
  src/main/resources/db/migration/V202402080448__create_notification_table.sql
  src/main/resources/db/migration/V202402080452__create_notification_setting_table.sql
  src/main/resources/db/migration/V202402090930__migration_member_to_notification_setting_table.sql
  src/main/resources/db/migration/V202402091030__create_notification_read_table.sql
  src/main/resources/db/migration/V202402151400__change_notification_table_and_notification_read_status.sql
  src/main/resources/db/migration/V202403011633__change_notification_setting_table.sql
  src/test/java/com/example/codebase/controller/FollowControllerTest.java
  src/test/java/com/example/codebase/controller/NotificationControllerTest.java
  src/test/java/com/example/codebase/controller/NotificationSettingControllerTest.java
Labels: D-1

#135 아트워크 포스트 데이터를 매거진으로 이관
  src/main/java/com/example/codebase/controller/ArtworkController.java
  src/main/java/com/example/codebase/controller/PostController.java
  src/main/java/com/example/codebase/domain/artwork/service/ArtworkService.java
  src/main/java/com/example/codebase/domain/magazine/entity/Magazine.java
  src/main/java/com/example/codebase/domain/magazine/entity/MagazineMedia.java
  src/main/java/com/example/codebase/domain/magazine/entity/MagazineMediaType.java
  src/main/java/com/example/codebase/domain/magazine/service/MagazineService.java
  src/main/java/com/example/codebase/domain/post/service/PostService.java
  src/main/resources/db/migration/V202403041510__add_visibled_column_to_magazine.sql
  src/main/resources/db/migration/V202403041540__migration_artwork_to_magazine.sql
  src/main/resources/db/migration/V202403041605__migration_post_to_magazine.sql
Labels: D-2

#136 매거진 메타데이터 다이나믹 필드 & 사용자가 작성한 매거진 조회 API
  src/main/java/com/example/codebase/controller/MagazineController.java
  src/main/java/com/example/codebase/domain/magazine/dto/MagazineRequest.java
  src/main/java/com/example/codebase/domain/magazine/dto/MagazineResponse.java
  src/main/java/com/example/codebase/domain/magazine/entity/Magazine.java
  src/main/java/com/example/codebase/domain/magazine/repository/MagazineRepository.java
  src/main/java/com/example/codebase/domain/magazine/service/MagazineService.java
  src/main/resources/db/migration/V202403041730__add_metadata_column_to_magazine.sql
  src/test/java/com/example/codebase/controller/MagazineControllerTest.java
Labels: D-2

#138 feat: member를 조회할떄 notification을 조회하는 문제 해결
  src/main/java/com/example/codebase/domain/member/entity/Member.java
  src/test/java/com/example/codebase/controller/MagazineLikeControllerTest.java
  src/test/java/com/example/codebase/controller/NotificationSettingControllerTest.java
Labels: D-1

#142 webhook을 이용한 서버 배포 알림 구현
  .github/workflows/dev-build.yml
  .github/workflows/prod-build.yml
  Dockerfile.dev
  Dockerfile.prod
  src/main/java/com/example/codebase/ArtBackendApplication.java
  src/main/java/com/example/codebase/infra/DeployAlertService.java
  src/main/resources/application.yml
Labels: D-1

#144 Artdev 158 be 팔로잉 매거진 리스트 기능
  src/main/java/com/example/codebase/controller/MagazineController.java
  src/main/java/com/example/codebase/domain/magazine/repository/MagazineRepository.java
  src/main/java/com/example/codebase/domain/magazine/service/MagazineService.java
  src/test/java/com/example/codebase/controller/MagazineControllerTest.java
Labels: D-1

#149 매거진 콘텐츠에 미디어 URL 첨부 프로시저 작성
  .github/workflows/test.yaml
  src/main/java/com/example/codebase/aop/AopForTransaction.java
  src/main/java/com/example/codebase/exception/LikePostDuplicatedRequestException.java
  src/main/resources/db/migration/V202403051151__application.sql
  src/test/java/com/example/codebase/controller/PostControllerTest.java
Labels: D-1

#150 Artscope 3.0.1 릴리즈
  .github/workflows/test.yaml
  README.md
  build.gradle
  src/main/java/com/example/codebase/annotation/DistributedLock.java
  src/main/java/com/example/codebase/aop/AopForTransaction.java
  src/main/java/com/example/codebase/aop/DistributedLockAop.java
  src/main/java/com/example/codebase/config/RedisConfig.java
  src/main/java/com/example/codebase/domain/post/entity/Post.java
  src/main/java/com/example/codebase/domain/post/repository/PostRepository.java
  src/main/java/com/example/codebase/domain/post/service/PostService.java
  src/main/java/com/example/codebase/exception/LikePostDuplicatedRequestException.java
  src/main/resources/db/migration/V202403051151__application.sql
  src/test/java/com/example/codebase/controller/PostControllerTest.java
  src/test/java/com/example/codebase/domain/post/service/PostServiceTest.java
Labels: 릴리즈

#154 Art 159 be 카테고리 계층화
  src/main/java/com/example/codebase/controller/MagazineCategoryController.java
  src/main/java/com/example/codebase/controller/MagazineController.java
  src/main/java/com/example/codebase/domain/magazine/dto/MagazineCategoryRequest.java
  src/main/java/com/example/codebase/domain/magazine/dto/MagazineCategoryResponse.java
  src/main/java/com/example/codebase/domain/magazine/dto/MagazineRequest.java
  src/main/java/com/example/codebase/domain/magazine/dto/MagazineResponse.java
  src/main/java/com/example/codebase/domain/magazine/entity/Magazine.java
  src/main/java/com/example/codebase/domain/magazine/entity/MagazineCategory.java
  src/main/java/com/example/codebase/domain/magazine/repository/MagazineCategoryRepository.java
  src/main/java/com/example/codebase/domain/magazine/service/MagazineCategoryService.java
  src/main/java/com/example/codebase/domain/magazine/service/MagazineService.java
  src/main/resources/db/migration/V202403051153__application.sql
  src/main/resources/db/migration/V202403051154__application.sql
  src/test/java/com/example/codebase/controller/CurationControllerTest.java
  src/test/java/com/example/codebase/controller/MagazineCategoryControllerTest.java
  src/test/java/com/example/codebase/controller/MagazineControllerTest.java
  src/test/java/com/example/codebase/controller/MagazineLikeControllerTest.java
Labels: D-2
